[package]
name = "Service-Control"
version = "0.0.4"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tui = "0.19.0"

[[bin]]
name = "cli"
path = "src/main.rs"
